"""add column shipping fee

Revision ID: 74542ab20014
Revises: a3f180ab4e67
Create Date: 2022-03-23 01:18:20.999818

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '74542ab20014'
down_revision = 'a3f180ab4e67'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('items', sa.Column('fee', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('items', 'fee')
    # ### end Alembic commands ###
