"""initialize entity

Revision ID: 7f7ef83e467c
Revises: 
Create Date: 2022-03-15 22:47:33.590937

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '7f7ef83e467c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('challanges',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=80), nullable=True, comment='1차'),
    sa.Column('start_date', sa.String(length=12), nullable=True, comment='2022-03-14'),
    sa.Column('end_date', sa.String(length=12), nullable=True, comment='2022-03-28'),
    sa.Column('out_count_limit', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('shop_name', sa.String(length=60), nullable=True),
    sa.Column('title', sa.String(length=60), nullable=True),
    sa.Column('discount_level', sa.String(length=10), nullable=True, comment='퍼센트 할인 50 p; 가격 할인 p 5000 (무료면 p 0)'),
    sa.Column('price', sa.Integer(), nullable=True),
    sa.Column('certification', sa.Boolean(), nullable=True),
    sa.Column('item_point', sa.Integer(), nullable=True),
    sa.Column('units', sa.Integer(), nullable=True),
    sa.Column('ticket_num', sa.Integer(), nullable=True),
    sa.Column('link', sa.String(length=500), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_items_id'), 'items', ['id'], unique=False)
    op.create_index(op.f('ix_items_title'), 'items', ['title'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.String(length=120), nullable=False),
    sa.Column('user_name', sa.String(length=20), nullable=True),
    sa.Column('gender', sa.String(length=4), nullable=True),
    sa.Column('back_phone_number', sa.String(length=4), nullable=True),
    sa.Column('phone_number', sa.String(length=16), nullable=True),
    sa.Column('email', sa.String(length=25), nullable=True),
    sa.Column('naver_id', sa.String(length=60), nullable=True),
    sa.Column('instagram_id', sa.String(length=60), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created', sa.DateTime(timezone=True), nullable=True),
    sa.Column('modified', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_table('challange_books',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('book_name', sa.String(length=80), nullable=True),
    sa.Column('publisher', sa.String(length=80), nullable=True),
    sa.Column('user_id', sa.String(length=120), nullable=True),
    sa.Column('challange_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['challange_id'], ['challanges.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('challange_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('challange_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.String(length=120), nullable=True),
    sa.Column('now_date', sa.String(length=12), nullable=True, comment='2022-03-15'),
    sa.Column('link', sa.String(length=500), nullable=True, comment='챌린지 인증 링크'),
    sa.Column('out_count', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=10), nullable=True, comment='SUCCESS/FAIL'),
    sa.Column('is_out', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['challange_id'], ['challanges.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pockets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.String(length=120), nullable=True),
    sa.Column('ticket_amount', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('purchases',
    sa.Column('user_id', sa.String(length=120), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('created', sa.DateTime(timezone=True), nullable=True),
    sa.Column('modified', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['item_id'], ['items.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'item_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('purchases')
    op.drop_table('pockets')
    op.drop_table('challange_logs')
    op.drop_table('challange_books')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_items_title'), table_name='items')
    op.drop_index(op.f('ix_items_id'), table_name='items')
    op.drop_table('items')
    op.drop_table('challanges')
    # ### end Alembic commands ###
