"""item revision

Revision ID: a3f180ab4e67
Revises: d8444d2776c4
Create Date: 2022-03-23 00:25:52.679542

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'a3f180ab4e67'
down_revision = 'd8444d2776c4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('items', sa.Column('image_url', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('items', 'image_url')
    # ### end Alembic commands ###
