"""delete challange_logs.is_out

Revision ID: d8444d2776c4
Revises: 754290cdab82
Create Date: 2022-03-16 00:02:42.843716

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'd8444d2776c4'
down_revision = '754290cdab82'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('challange_logs', 'is_out')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('challange_logs', sa.Column('is_out', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
