"""purchase status 추가

Revision ID: da44f3318728
Revises: 74542ab20014
Create Date: 2022-03-23 12:07:53.128991

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'da44f3318728'
down_revision = '74542ab20014'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('purchases', sa.Column('status', sa.String(length=12), nullable=True, comment='CONFIRM/SUBMIT/DELETE/PURCHASED'))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('purchases', 'status')
    # ### end Alembic commands ###
