[tool.poetry]
name = "fastapi_app"
version = "0.1.0"
description = "dadok server"
authors = ["jinhyeok15 <mivv@read-manybooks.com>"]

[tool.poetry.dependencies]
python = "^3.8"
uvicorn = "*"
fastapi = "*"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"